FROM php:5.6.30-apache

RUN apt-get update && apt-get install -y libc-client-dev \
    libkrb5-dev && rm -r /var/lib/apt/lists/*
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap
RUN docker-php-ext-install mysql
RUN docker-php-ext-install mysqli
RUN apt-get update \
    && apt-get install -y zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip

## Crontab
RUN apt-get update && apt-get install -y cron rsyslog
RUN apt-get clean && rm -rf /tmp/* /var/tmp/* && rm -rf /var/lib/apt/lists/*
ADD crontab /etc/cron.d/crontab
RUN rm -Rf /etc/cron.daily  && \
    rm -Rf /etc/cron.weekly && \
    rm -Rf /etc/cron.monthly && \
    rm -Rf /etc/cron.hourly && \
    chmod a+x /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab

RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

RUN mkdir -p /var/www/html/logs/
RUN touch /var/www/html/logs/vtigercrm_app.log
RUN touch /var/www/html/logs/vtigercrm_cron.log
RUN touch /var/www/html/logs/vtigercrm_error.log

ADD php.ini /usr/local/etc/php/php.ini

COPY foreground.sh /usr/local/bin/
CMD ["foreground.sh"]